services:
  # Redis service for caching
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]

  # FastAPI backend service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    depends_on: [redis]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - db-data:/app  # persist SQLite DB
    ports: ["8000:8000"]

  # Streamlit frontend service
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    restart: unless-stopped
    depends_on: [api]
    environment:
      API_URL: http://api:8000
    ports: ["8501:8501"]

# Named volume for database persistence
volumes:
  db-data:
